### ISSUE TITLE
ability to use oscilloscope with html5 audio (not get user media)

### ISSUE THREAD

**Issue by heaversm** [mathiasvr/audio-oscilloscope#1]
Hi! Just wondering if there's a way to load an html5 audio source as the source for the oscilloscope instead of a get user media stream? I currently get this error:

<img width="693" alt="screen shot 2017-05-30 at 8 57 22 am" src="https://cloud.githubusercontent.com/assets/520541/26592601/124ff1cc-4516-11e7-99a7-917495ea3d41.png">

**Comment by heaversm** [comment]
Realized this is an issue with html5 audio api itself, not oscilloscope. I should be using `createMediaElementSource` instead of `createMediaStreamSource`. Closing.

**Comment by mathiasvr** [comment]
Hi, I was just going through some old code, but I only found loading audio through ajax.
If you have an example of how to do it with html5 audio, it could be nice to add it to the readme 😃

**Comment by heaversm** [comment]
Cool - yeah - here's how I did it. I'm using the twilio API, so my voice recordings are coming from there. Init as normal, with the only difference being the:

```
initScope = function () {
        context = new window.AudioContext()
        canvas = document.querySelector('.visualizer')
        audio = document.querySelector('.audio') //or audio = $('.audio')[0] if using jQuery

        var options = {
            stroke: 1,    // size of the wave
            buffer: 1024  // buffer size ranging from 32 to 2048
        }

        scope = new Oscilloscope(canvas, options)

        var source = context.createMediaElementSource(audio) //create media element source on your audio html element
        scope.addSignal(source, '#ffffff')
    }
```

Then I also had to add a crossOrigin property to the audio element because it was coming from twilio to prevent getting access restrictions:

```
audio.crossOrigin = "anonymous"
```
