### ISSUE TITLE
example fails because oscilloscope.umd.js is not present

### ISSUE THREAD

**Issue by swharden** [mathiasvr/audio-oscilloscope#9]
FYI, the example fails because it requires a file not contained in the repo. 

https://github.com/mathiasvr/audio-oscilloscope/blob/9ac34fbf491718c4f1472b55a364cddfaef8cb69/examples/index.html#L24

I know this can be built, but I'd expect the example to run right away. Consider making the demo self-contained, so this project can be evaluated without setting up a build environment

**Comment by mathiasvr** [comment]
Fixed by #10.
